id: I4F9555C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:12:22+00:00'
last_modified: '2022-06-08T12:06:00.111874+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3384
  title: མངོན་པ་ཀུན་བཏུས་ཀྱི་སྡོམ་བྱང་དང་མཆན་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C040:
      image_group_id: I3CN3469
      title: ''
      total_pages: 420
      order: 1
      base_file: C040.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
