id: P009589
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:34.614997
source_metadata:
  id: bdr:W3CN3384
  title: མངོན་པ་ཀུན་བཏུས་ཀྱི་སྡོམ་བྱང་དང་མཆན་འགྲེལ།
  author: ''
  volumes:
    2e5063e574c94ebb82f8912d579d1fff:
      image_group_id: I3CN3469
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
